# Site settings
title: A Place For Everybody
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Quantifying the statement "be excellent to each other"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "placeforeverybody.org" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

#Github Pages Settings
highlighter: pygments
safe: true
lsi: false

# Build settings
markdown: kramdown
