# Site settings
title: A Place For Everybody
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Quantifying "Be Excellent To Each Other"
baseurl: "/placeforeverybody" # the subpath of your site, e.g. /blog/
url: "placeforeverybody.org" # the base hostname & protocol for your site

#Github Pages Settings
highlighter: pygments
safe: true
lsi: false

# Build settings
markdown: kramdown
